### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Missa-Fissa** [CodingCryptoTrading/dca-crypto-bot#1]
Is it possible to have multiple exchange listings instead of just 1 exchange?

**Comment by Missa-Fissa** [comment]
Also, Kraken Balance checks returns None, this is giving an issue

**Comment by CodingCryptoTrading** [comment]
Sorry for the late reply,
only one exchange can be used at a time. A workaround is to run multiple instances of the bot, each with a different exchange.

Unfortunately, I don't have a Kraken account. Can you post the error message?

**Comment by Missa-Fissa** [comment]
Error message: "TypeError: argument of type 'NoneType' is not iterable"

The bot says "None" at all free and used balances (while there is balance) and can't seem to go through with 'None'.

**Comment by CodingCryptoTrading** [comment]
It seems that the Kraken API returns total only (no free or used balance). 

I just uploaded a fix (https://github.com/CodingCryptoTrading/dca-crypto-bot/commit/6c471dfe8c067d7474635e839c2e6215d0cec8d3). Please, give it a try and let me know if it works.

**Comment by CodingCryptoTrading** [comment]
Btw, I just merged the develop branch. The bot now works on FTX too, and it should work with other exchanges as well.

**Comment by Missa-Fissa** [comment]
Awesome!
